# Обзор основных функций библиотеки numpy

In [1]:
import numpy as np
print(np.__version__)

1.13.3


In [6]:
a = np.array(range(6))

In [7]:
a

array([0, 1, 2, 3, 4, 5])

In [8]:
a.reshape((2, 3))

array([[0, 1, 2],
       [3, 4, 5]])

In [9]:
a.reshape((3, 2))

array([[0, 1],
       [2, 3],
       [4, 5]])

<hr>

In [10]:
a = np.array([[1,2],[3,4]])
b = np.array([[1,2,3], [4,5,6]])
print(np.dot(a, b))

[[ 9 12 15]
 [19 26 33]]


In [12]:
a = np.array([
    [5, -4, -8],
    [0, 1, 0], 
    [-3, 6, 4],
])

b = np.array([
    [-4, -7, -1],
    [-5, 8, 9],
    [-1, 2, -9],
])

print(np.dot(a, b))

[[  8 -83  31]
 [ -5   8   9]
 [-22  77  21]]


<hr>

In [16]:
a = np.array([[1,2],[3,4]])
b = np.array([[1,2], [3,4]])

print(a + b)
print('-'  * 10)
print(a - b)

[[2 4]
 [6 8]]
----------
[[0 0]
 [0 0]]


<hr>

In [17]:
a = np.array([[1,2,3],[4,5,6]])
print(a)
print('-' * 10)
print(a.transpose())

[[1 2 3]
 [4 5 6]]
----------
[[1 4]
 [2 5]
 [3 6]]


<hr>

In [18]:
a.shape

(2, 3)