In [2]:
import numpy as np
import numpy as numpy
import matplotlib.pyplot as plt
import scipy.special

In [29]:
'''WRONG'''
class NN:
    
    def __init__(self, inodes, hnodes, onodes, lr = 0.1):
        self.wih = np.random.rand(hnodes, inodes)
        self.who = np.random.rand(onodes, hnodes)
        
        self.lr = lr
    
    def sigmoid(self, x):
        return 1 / (1 + np.exp(-x))
    
    def predict(self, x):
        h_z = np.dot(self.wih, x)
        h_o = self.sigmoid(h_z)
        
        o_z = np.dot(self.who, h_o)
        o_o = self.sigmoid(o_z)
        return o_o
    
    def train(self, x, y):
        h_z = np.dot(self.wih, x)
        h_o = self.sigmoid(h_z)
        
        o_z = np.dot(self.who, h_o)
        o_o = self.sigmoid(o_z)
        
        delta = (o_o - y) * (o_o * (1 - o_o))
        delta_who = np.dot(delta, h_o.T)
        delta_wih = np.dot(np.dot(self.who.T, delta) * (h_o * (1 - h_o)), x.T)
        print(delta_wih)
        self.who -= 0.1 * delta_who
        self.wih -= 0.1 * delta_wih


In [30]:
nn = NN(2,4,2)
x = np.array([1,1], ndmin=2).T
y = np.array([0,1], ndmin=2).T
for _ in range(400):
    nn.train(x,y)

[[ 0.00585936  0.00585936]
 [ 0.01852035  0.01852035]
 [ 0.01572934  0.01572934]
 [ 0.00136548  0.00136548]]
[[ 0.00571256  0.00571256]
 [ 0.01857558  0.01857558]
 [ 0.01579608  0.01579608]
 [ 0.00124436  0.00124436]]
[[ 0.00555792  0.00555792]
 [ 0.01862263  0.01862263]
 [ 0.01585522  0.01585522]
 [ 0.00111533  0.00111533]]
[[ 0.00539526  0.00539526]
 [ 0.01866105  0.01866105]
 [ 0.01590631  0.01590631]
 [ 0.00097824  0.00097824]]
[[ 0.00522443  0.00522443]
 [ 0.01869035  0.01869035]
 [ 0.01594888  0.01594888]
 [ 0.00083297  0.00083297]]
[[ 0.00504529  0.00504529]
 [ 0.01871007  0.01871007]
 [ 0.01598247  0.01598247]
 [ 0.00067941  0.00067941]]
[[ 0.00485773  0.00485773]
 [ 0.01871973  0.01871973]
 [ 0.01600664  0.01600664]
 [ 0.00051746  0.00051746]]
[[ 0.00466167  0.00466167]
 [ 0.01871887  0.01871887]
 [ 0.01602091  0.01602091]
 [ 0.00034706  0.00034706]]
[[ 0.00445705  0.00445705]
 [ 0.01870703  0.01870703]
 [ 0.01602485  0.01602485]
 [ 0.00016817  0.00016817]]
[[  4.24382592e-03 

In [31]:
nn.predict(x)

array([[ 0.09456619],
       [ 0.92784063]])